### ISSUE TITLE
Exception, while dumping SQL on server side for FLOW only projects

### ISSUE THREAD

**Issue by erickloss** [sandstorm/synco#34]
reproduce
connect to a server with a running flow application **without** Neos.
```
curl https://sandstorm.github.io/synco/serve | sh -s -
```

It seem's you exclude the table `neos_media_domain_model_thumbnail` which fails the command if this table does not exist.

Scenarios, where this is possible:
 - pure Flow Project without Neos
 - Neos Project without Media Module (if this is even possible)

```
  FATAL   could not create SQL dump: error registering database: Error 1146: Table 'neos.neos_media_domain_model_thumbnail' doesn't exist
panic:

goroutine 1 [running]:
github.com/pterm/pterm.checkFatal(...)
	github.com/pterm/pterm@v0.12.49/prefix_printer.go:348
github.com/pterm/pterm.(*PrefixPrinter).Printfln(0xc90b20, {0x8e9dcc, 0x1d}, {0xc000155a18, 0x1, 0x1})
	github.com/pterm/pterm@v0.12.49/prefix_printer.go:290 +0x1e5
github.com/sandstorm/synco/v2/pkg/common/commonServe.DatabaseDump(0xc00009e780, 0xc0000800f0, 0xc00017c5a0)
	github.com/sandstorm/synco/v2@v2.0.1/pkg/common/commonServe/databaseDump.go:32 +0x14c
github.com/sandstorm/synco/v2/pkg/frameworks/flowServe.flowServe.Serve({}, 0xc00009e780)
	github.com/sandstorm/synco/v2@v2.0.1/pkg/frameworks/flowServe/flowServe.go:159 +0x1c6
github.com/sandstorm/synco/v2/pkg/serve/cmd.init.func1(0xc0000c4200?, {0x8db693?, 0x4?, 0x8db697?})
	github.com/sandstorm/synco/v2@v2.0.1/pkg/serve/cmd/source-cmd.go:60 +0x44e
github.com/spf13/cobra.(*Command).execute(0xc927c0, {0xcf9c40, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x867
github.com/spf13/cobra.(*Command).ExecuteC(0xc924e0)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/sandstorm/synco/v2/lite/cmd-lite.Execute()
	github.com/sandstorm/synco/v2@v2.0.1/lite/cmd-lite/root-lite.go:45 +0x48
main.main()
	github.com/sandstorm/synco/v2@v2.0.1/lite/main-lite.go:8 +0xf
```

**Comment by erickloss** [comment]
running the command with the `--all` flag workarounds the issue.
