### ISSUE TITLE
Error with file type PublicFiles: error on downloading

### ISSUE THREAD

**Issue by breadlesscode** [sandstorm/synco#6]
First, thanks a lot for this package! Its a missing piece for the daily development <3 

I tried it on our server as the readme says. But i got the following error:

```
  FATAL   Error with file type PublicFiles: error on downloading <BASE>/./Web/_Resources/Persistent to Resources/_/R/e/s/_Resources: file meta.json.enc not found                                           
 [0/4096]  0% | 1spanic: 

goroutine 1 [running]:
github.com/pterm/pterm.checkFatal(...)
        github.com/pterm/pterm@v0.12.49/prefix_printer.go:348
github.com/pterm/pterm.(*PrefixPrinter).Printfln(0x18963e0, {0x1509702, 0x1b}, {0xc0001b16d8, 0x2, 0x2})
        github.com/pterm/pterm@v0.12.49/prefix_printer.go:290 +0x1e8
github.com/sandstorm/synco/pkg/receive/cmd.glob..func1(0x18980c0?, {0xc000072200?, 0x2?, 0x2?})
        github.com/sandstorm/synco@v1.0.0/pkg/receive/cmd/receive-cmd.go:90 +0xab9
github.com/spf13/cobra.(*Command).execute(0x18980c0, {0xc0000721c0, 0x2, 0x2})
        github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1897e40)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
github.com/sandstorm/synco/cmd.Execute()
        github.com/sandstorm/synco@v1.0.0/cmd/root.go:47 +0x85
main.main()
        github.com/sandstorm/synco@v1.0.0/main.go:23 +0xa5
```

Am I doing something wrong? 

Thanks again for your hard work!

**Comment by skurfuerst** [comment]
@breadlesscode what did you specify as base URL? I feel that something is wrong there (and of course we need to improve error reporting :D )

**Comment by breadlesscode** [comment]
Hi,

I cant post the real URL, but the format of the base URL is `project.beta.domain.com`. 

It prompts the correct URL after I entered this:
```
SUCCESS  Found correct base URL at https://project.beta.domain.com
```

But the path in the meta.json seems to be invalid (see error message)

Error:
``` 
FATAL   Error with file type PublicFiles: error on downloading <BASE>/./Web/_Resources/Persistent to Resources/_/R/e/s/_Resources: file meta.json.enc not found
```
